-- MySQL Script generated by MySQL Workbench
-- ven. 06 mars 2020 10:37:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `idPerson` VARCHAR(40) NOT NULL,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `email` VARCHAR(120) NULL,
  `password` VARCHAR(255) NULL,
  `phoneNumber` VARCHAR(15) NULL,
  `function` VARCHAR(45) NULL DEFAULT NULL,
  `localisation` VARCHAR(45) NULL,
  `qrCode` VARCHAR(200) NULL,
  `subcription` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `idlog` VARCHAR(50) NOT NULL,
  `date` DATE NULL,
  `idService` VARCHAR(50) NULL,
  `late` TINYINT NULL,
  `idPerson` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idlog`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC) VISIBLE,
  UNIQUE INDEX `idlog_UNIQUE` (`idlog` ASC) VISIBLE,
  CONSTRAINT `fk_idPerson_1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `idService` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `demo` TINYINT NULL DEFAULT 0,
  `price` DOUBLE NULL,
  `category` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`idService`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idOrders` VARCHAR(50) NOT NULL,
  `price` DOUBLE NOT NULL,
  `idPerson` VARCHAR(50) NOT NULL,
  `idService` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idOrders`),
  UNIQUE INDEX `idService_UNIQUE` (`idService` ASC) VISIBLE,
  UNIQUE INDEX `idOrders_UNIQUE` (`idOrders` ASC) VISIBLE,
  UNIQUE INDEX `idClient_UNIQUE` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_idPerson_2`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idService_2`
    FOREIGN KEY (`idService`)
    REFERENCES `mydb`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estimate` (
  `idestimate` VARCHAR(50) NOT NULL,
  `pdf` VARCHAR(100) NULL,
  `idService` VARCHAR(50) NULL,
  `status` INT NULL,
  `price` DOUBLE NULL,
  `idPerson` VARCHAR(50) NOT NULL,
  `dateEstimate` DATE NULL,
  PRIMARY KEY (`idestimate`),
  UNIQUE INDEX `idestimate_UNIQUE` (`idestimate` ASC) VISIBLE,
  UNIQUE INDEX `idClient_UNIQUE` (`idPerson` ASC) VISIBLE,
  INDEX `fk_idService_1_idx` (`idService` ASC) VISIBLE,
  CONSTRAINT `fk_idService_1`
    FOREIGN KEY (`idService`)
    REFERENCES `mydb`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPerson_1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bill` (
  `idBill` VARCHAR(50) NOT NULL,
  `price` VARCHAR(45) NULL,
  `pdf` VARCHAR(45) NULL,
  `creationDate` DATE NULL,
  `idOrders` VARCHAR(50) NULL,
  PRIMARY KEY (`idBill`),
  INDEX `fk_idOrders_1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_idOrders_1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `mydb`.`orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

